# Generated by Django 5.1.1 on 2024-09-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('induction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
