# Generated by Django 5.1.1 on 2024-09-09 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('induction', '0002_applicant_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
